// angular-client/src/app/components/config-form/aplicar-pagos/aplicar-pagos.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-aplicar-pagos',
  templateUrl: './aplicar-pagos.component.html',
  styleUrls: ['./aplicar-pagos.component.scss']
})
export class AplicarPagosComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<section>
  <div class="section-header">
    Aplicación de Pagos
  </div>
  <div class="section-content d-flex flex-column align-items-end">
    <div class="main-input-group">
      <label for="config-ap-fondeador">Fondeador</label>
      <input id="config-ap-fondeador" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-saldoInicial">Saldo Inicial</label>
      <input id="config-ap-saldoInicial" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-gtsCobranza">Gts. Cobranza</label>
      <input id="config-ap-gtsCobranza" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-moratorios">Moratorios</label>
      <input id="config-ap-moratorios" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-seguroDeuda">Seguro Deuda</label>
      <input id="config-ap-seguroDeuda" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-seguroAuto">Seguro Auto</label>
      <input id="config-ap-seguroAuto" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-gps">GPS</label>
      <input id="config-ap-gps" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-admon">Admon</label>
      <input id="config-ap-admon" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-intereses">Intereses</label>
      <input id="config-ap-intereses" type="text">
    </div>
    <div class="main-input-group">
      <label for="config-ap-fondeador2">Fondeador</label>
      <input id="config-ap-fondeador2" type="text">
    </div>
  </div>
</section>

// client/src/components/ConfigForm/AplicarPagos.vue
<template>
  <section>
    <div class="section-header">
      Aplicación de Pagos
    </div>
    <div class="section-content d-flex flex-column align-items-end">
      <div class="main-input-group">
        <label for="config-ap-fondeador">Fondeador</label>
        <input id="config-ap-fondeador" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-saldoInicial">Saldo Inicial</label>
        <input id="config-ap-saldoInicial" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-gtsCobranza">Gts. Cobranza</label>
        <input id="config-ap-gtsCobranza" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-moratorios">Moratorios</label>
        <input id="config-ap-moratorios" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-seguroDeuda">Seguro Deuda</label>
        <input id="config-ap-seguroDeuda" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-seguroAuto">Seguro Auto</label>
        <input id="config-ap-seguroAuto" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-gps">GPS</label>
        <input id="config-ap-gps" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-admon">Admon</label>
        <input id="config-ap-admon" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-intereses">Intereses</label>
        <input id="config-ap-intereses" type="text">
      </div>
      <div class="main-input-group">
        <label for="config-ap-fondeador2">Fondeador</label>
        <input id="config-ap-fondeador2" type="text">
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'AplicarPagos'
};
</script>

<style scoped>
.main-input-group:first-child {
  margin-bottom: 0.75rem;
}
</style>
