// angular-client/src/app/components/config-form/ref-bancarias/ref-bancarias.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-ref-bancarias',
  templateUrl: './ref-bancarias.component.html',
  styleUrls: ['./ref-bancarias.component.scss']
})
export class RefBancariasComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<section>
  <div class="section-header">Referencias Bancarias</div>
  <div class="section-content d-flex flex-column align-items-end">
    <label class="d-block text-align-left" style="align-self: center">Caracteres</label>
    <div class="main-input-group">
      <label for="config-refbanc-max">Máximo</label>
      <input id="config-refbanc-max">
    </div>
    <div class="main-input-group">
      <label for="config-refbanc-min">Mínimo</label>
      <input id="config-refbanc-min">
    </div>
  </div>
</section>

// client/src/components/ConfigForm/RefBancarias.vue
<template>
<section>
  <div class="section-header">Referencias Bancarias</div>
  <div class="section-content d-flex flex-column align-items-end">
    <label class="d-block text-align-left" style="align-self: center">Caracteres</label>
    <div class="main-input-group">
      <label for="config-refbanc-max">Máximo</label>
      <input id="config-refbanc-max">
    </div>
    <div class="main-input-group">
      <label for="config-refbanc-min">Mínimo</label>
      <input id="config-refbanc-min">
    </div>
  </div>
</section>
</template>

<script>
export default {
name: "RefBancarias"
}
</script>

<style scoped>

</style>
