// angular-client/src/app/components/config-form/seguros-autos/seguros-autos.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-seguros-autos',
  templateUrl: './seguros-autos.component.html',
  styleUrls: ['./seguros-autos.component.scss']
})
export class SegurosAutosComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<section>
  <div class="section-header">Seguros Autos</div>
  <div class="section-content">
    <div class="main-main-input-group d-flex justify-content-between">
      <div class="main-input-group">
        <label class="d-block" for="config-segAuto-compa">Compañía</label>
        <input id="config-segAuto-compa">
      </div>
      <div class="main-input-group">
        <label class="d-block" for="config-segAuto-comision">Comisión</label>
        <input id="config-segAuto-comision">
      </div>
    </div>
    <div class="main-main-input-group">
      <div class="main-input-group d-block">
        <label for="config-segAuto-razonSocial">RazónSocial</label>
        <input id="config-segAuto-razonSocial">
      </div>
    </div>
  </div>
</section>

// client/src/components/ConfigForm/SegurosAutos.vue
<template>
<section>
  <div class="section-header">Seguros Autos</div>
  <div class="section-content">
    <div class="main-main-input-group d-flex justify-content-between">
      <div class="main-input-group">
        <label class="d-block" for="config-segAuto-compa">Compañía</label>
        <input id="config-segAuto-compa">
      </div>
      <div class="main-input-group">
        <label class="d-block" for="config-segAuto-comision">Comisión</label>
        <input id="config-segAuto-comision">
      </div>
    </div>
    <div class="main-main-input-group">
      <div class="main-input-group d-block">
        <label for="config-segAuto-razonSocial">RazónSocial</label>
        <input id="config-segAuto-razonSocial">
      </div>
    </div>
  </div>
</section>
</template>

<script>
export default {
name: "SegurosAutos"
}
</script>

<style scoped>

</style>
