// angular-client/src/app/components/main-form/aplicar-op/aplicar-op.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { AplicarOpService } from '../../../services/aplicar-op/aplicar-op.service';
import { Subscription } from 'rxjs';
import { AplicarOp } from '../../../models/aplicar-operacion.model';

@Component({
  selector: 'app-aplicar-op',
  templateUrl: './aplicar-op.component.html',
  styleUrls: ['./aplicar-op.component.scss']
})
export class AplicarOpComponent implements OnInit, OnDestroy {
  aplicarOp: AplicarOp;
  private aplicarOpSub: Subscription;
  constructor(private aplicarOpService: AplicarOpService) { }

  ngOnInit(): void {
    this.aplicarOpSub = this.aplicarOpService.aplicarOpChanged
      .subscribe((aplicarOp) => {
        this.aplicarOp = aplicarOp;
        console.log(this.aplicarOp);
      });
  }

  ngOnDestroy(): void {
    this.aplicarOpSub.unsubscribe();
  }

  update(key: string, $event: Event): void {
    this.aplicarOpService.modify(key, ($event.target as HTMLInputElement).value);
  }
}

<!-- Aplicar Operación -->
<section>
  <div class="section-header">
    Aplicar Operación
  </div>
  <div class="section-content d-flex flex-column align-items-end">
    <div class="main-input-group">
      <label for="input-chequera">Chequera</label>
      <input id="input-chequera" type="text" [value]="aplicarOp?.chequera || ''"
        (input)="update('chequera', $event)"
      >
    </div>
    <div class="main-input-group">
      <label for="input-sucursal">Sucursal</label>
      <input id="input-sucursal" type="text" [value]="aplicarOp?.sucursal || ''" (input)="update('chequera', $event)">
    </div>
  </div>
</section>

// client/src/components/sections/AplicarOp.vue
<template>
  <section>
    <div class="section-header">
      Aplicar Operación
    </div>
    <div class="section-content d-flex flex-column align-items-end">
      <div class="main-input-group">
        <label for="input-chequera">Chequera</label>
        <input id="input-chequera" type="text">
      </div>
      <div class="main-input-group">
        <label for="input-sucursal">Sucursal</label>
        <input id="input-sucursal" type="text">
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({})
export default class AplicarOp extends Vue {}
</script>
