// angular-client/src/app/components/main-form/lote-autos/lote-autos.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-lote-autos',
  templateUrl: './lote-autos.component.html',
  styleUrls: ['./lote-autos.component.scss']
})
export class LoteAutosComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<!-- Lotes Autos -->
<section>
  <div class="section-header">
    Lote Autos
  </div>
  <div class="section-content d-flex flex-column align-items-end">
    <div class="main-input-group d-block mb-1" style="width: 100%">
      <label for="input-razonSocial">Razón Social</label>
      <input id="input-razonSocial" type="text">
    </div>
    <div class="d-flex">
      <div><label class="d-block m-0 mr-2 text-center" style="width: 75px;">Comisión</label></div>
      <div><label class="d-block m-0 text-center" style="width: 75px;">Importe</label></div>
    </div>
    <div class="main-input-group">
      <label for="input-sinIVA">Sin IVA</label>
      <input id="input-sinIVA" type="text">
      <label for="input-impSinIVA"></label>
      <input id="input-impSinIVA" type="text">
    </div>
    <div class="main-input-group mb-1">
      <label for="input-conIVA">Con IVA</label>
      <input id="input-conIVA" type="text">
      <label for="input-impConIVA"></label>
      <input id="input-impConIVA" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-lineaVenta">LineaVenta</label>
      <input id="input-lineaVenta" type="text">
    </div>
  </div>
</section>

// client/src/components/sections/LoteAutos.vue
<template>
  <section>
    <div class="section-header">
      Lote Autos
    </div>
    <div class="section-content d-flex flex-column align-items-end">
      <div class="main-input-group field-wrap-vertical mb-1" style="width: 100%">
        <label for="input-razonSocial">Razón Social</label>
        <input id="input-razonSocial" type="text">
      </div>
      <div class="labels-flex">
        <div><label>Comisión</label></div>
        <div><label>Importe</label></div>
      </div>
      <div class="main-input-group">
        <label for="input-sinIVA">Sin IVA</label>
        <input id="input-sinIVA" type="text">
        <label for="input-impSinIVA"></label>
        <input id="input-impSinIVA" type="text">
      </div>
      <div class="main-input-group mb-1">
        <label for="input-conIVA">Con IVA</label>
        <input id="input-conIVA" type="text">
        <label for="input-impConIVA"></label>
        <input id="input-impConIVA" type="text">
      </div>
      <div class="main-input-group">
        <label for="input-lineaVenta">LineaVenta</label>
        <input id="input-lineaVenta" type="text">
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({})
export default class LoteAutos extends Vue {}
</script>


<style scoped>
.mb-1 {
  margin-bottom: 1rem;
}

.field-wrap-vertical {
  width: 100%;
  display: flex;
  flex-direction: column;
}

.field-wrap-vertical input {
  width: 100%;
}

.labels-flex {
  display: flex;
}

.labels-flex > div {
  width: 75px;
}

.labels-flex > div:last-child {
  margin-left: 4px;
}
</style>
