// client/src/components/sections/Financiamiento.vue
<template>
  <section>
    <div class="section-header">
      Financiamiento
    </div>
    <div class="section-content d-flex flex-column align-items-end">
      <div class="d-flex flex-column mb-3 text-center">
        <label for="input-producto">Producto
          <span class="fas fa-info-circle"
                v-b-tooltip.hover.right="'Escriba producto para buscarlo'"
          ></span>
        </label>
        <div class="main-input-group input-group input-group-sm">
          <input 
            id="input-producto"
            type="text"
            :value="producto.producto"
            @input="update('producto', $event)"
            @blur="checkProducto()"
            @keyup.enter="checkProducto()"
            style="width: 100px;"
          >
          <div class="input-group-append">
            <b-button
              type="button" 
              @click="checkProducto()"
              id="button-search"
              style="height: 1.5rem;"
              variant="secondary"
            >
              <i class="fas fa-search"></i>
            </b-button>
          </div>
        </div>
      </div><!--d-flex flex-column mr-2-->
      <div class="main-input-group">
        <label for="input-fondeador">Fondeador</label>
        <input id="input-fondeador" type="text" :value="producto.fondeador" @input="update('fondeador',$event)">
      </div>
      <div class="main-input-group">
        <label for="input-noPagos">No. Pagos</label>
        <input id="input-noPagos" type="text" :value="producto.noPagos" @input="update('noPagos',$event)">
      </div>
      <div class="main-input-group">
        <label for="input-periodicidad">Periodicidad</label>
        <input id="input-periodicidad" type="text" :value="producto.pptipo" @input="update('pptipo',$event)">
      </div>
      <div class="main-input-group">
        <label for="input-valorOperacion">Valor Operación</label>
        <input id="input-valorOperacion" type="text" :value="producto.valorOperacion" @input="update('valorOperacion',$event)">
      </div>
      <div class="main-input-group">
        <label for="input-productoTipo">Producto Tipo</label>
        <input id="input-productoTipo" type="text" :value="producto.tipo" @input="update('tipo',$event)">
      </div>
      <div class="main-input-group">
        <label for="input-tasaAnual">Tasa Anual</label>
        <input id="input-tasaAnual" class="text-center" type="text" :value="producto.tasa.toFixed(2) + '%'" @input="update('tasa',$event)">
      </div>
      <div style="width: 75px; margin-top: 10px; text-align: center;"><label>Importe</label></div>
      <div class="main-input-group">
        <label for="input-anticipo">Anticipo</label>
        <input id="input-anticipo" class="text-center" type="text" :value="producto.anticipo.toFixed(2) + '%'" @input="update('anticipo',$event)">
        <label class="block-label" for="input-impAnticipo"></label>
        <input disabled id="input-impAnticipo" type="text" :value="anticipo">
      </div>
      <div class="main-input-group">
        <label for="input-seguroDeuda">SeguroDeuda</label>
        <input id="input-seguroDeuda" class="text-center" type="text" :value="producto.segurodeuda.toFixed(2)" @input="update('segurodeuda',$event)">
        <label for="input-impSeguroDeuda"></label>
        <input disabled id="input-impSeguroDeuda" type="text" :value="producto.segurodeuda.toFixed(2)">
      </div>
      <div class="main-input-group">
        <label for="input-apertura">Apertura</label>
        <input id="input-apertura" class="text-center" type="text" :value="producto.apertura.toFixed(2) + '%'" @input="update('apertura',$event)">
        <label for="input-impApertura"></label>
        <input disabled id="input-impApertura" type="text" :value="apertura">
      </div>
      <div class="main-input-group">
        <label for="input-deposito">Depósito</label>
        <input id="input-deposito" class="text-center" type="text" :value="producto.deposito.toFixed(2) + '%'" @input="update('deposito',$event)">
        <label for="input-impDeposito"></label>
        <input disabled id="input-impDeposito" type="text" :value="deposito">
      </div>
      <div class="main-input-group">
        <label for="input-admin">Administración</label>
        <input id="input-admin" class="text-center" type="text" :value="producto.administracion.toFixed(2)" @input="update('administracion',$event)">
        <label for="input-impAdmin"></label>
        <input disabled id="input-impAdmin" type="text" :value="producto.administracion.toFixed(2)">
      </div>
      <div class="main-input-group">
        <label for="input-gps">GPS</label>
        <input id="input-gps" class="text-center" type="text" :value="producto.gps.toFixed(2)" @input="update('gps',$event)">
        <label for="input-impGps"></label>
        <input disabled id="input-impGps" type="text" :value="producto.gps.toFixed(2)">
      </div>
      <div class="main-input-group">
        <label for="input-seguroAuto">SeguroAuto</label>
        <input id="input-seguroAuto" class="text-center" type="text" :value="producto.seguroauto.toFixed(2)" @input="update('seguroauto',$event)">
        <label for="input-impSeguroAuto"></label>
        <input disabled id="input-impSeguroAuto" type="text" :value="producto.seguroauto.toFixed(2)">
      </div>
      <div class="main-input-group" style="margin-bottom: 10px;">
        <label for="input-valorRescate">ValorRescate</label>
        <input id="input-valorRescate" class="text-center" type="text" :value="producto.valorRescate.toFixed(2)" @input="update('valorRescate',$event)">
        <label for="input-impValorRescate"></label>
        <input disabled id="input-impValorRescate" type="text" :value="producto.valorRescate.toFixed(2)">
      </div>
      <div class="main-input-group">
        <label for="input-descuento">Descuento</label>
        <input id="input-descuento" type="text">
        <label for="input-impDescuento"></label>
        <input disabled id="input-impDescuento" type="text">
      </div>
      <div style="text-align: right;"><hr style="border-top: #000000 solid 1px; width: 75px"></div>
      <div class="main-input-group">
        <label for="input-total">Total Primer Pago</label>
        <input id="input-total" type="text" :value="primerPago">
      </div>
    </div><!-- section-content -->
  </section>
</template>

<script>
import { Component, Vue } from 'vue-property-decorator';
import { mapActions, mapMutations, mapState } from 'vuex';

export default{
  name: 'producto',
  computed: {
    ...mapState(['producto']),
    anticipo() {
      return (this.producto.anticipo/100) * this.producto.valorOperacion;
    },
    apertura() {
      return (this.producto.apertura/100) * this.producto.valorOperacion;
    },
    deposito() {
      return (this.producto.deposito/100) * this.producto.valorOperacion;
    },
    primerPago() {
      //console.log(this.anticipo);console.log(this.producto.segurodeuda);console.log(this.apertura);console.log(this.deposito);console.log(this.producto.administracion);console.log(this.producto.gps);console.log(this.producto.seguroauto);
      return (parseFloat(this.anticipo)+parseFloat(this.producto.segurodeuda)+parseFloat(this.apertura)+parseFloat(this.deposito)+parseFloat(this.producto.administracion)+parseFloat(this.producto.gps)+parseFloat(this.producto.seguroauto)).toFixed(2);
    }
  },
  methods: {
    ...mapActions(['fetchProducto']),
    ...mapMutations(['setProducto']),
    update(key, event) {
      this.producto[key] = event.target.value;
      this.setProducto({ [key]: event.target.value });
    },
    checkProducto(){
      if(this.producto.producto==='auto'){
        this.foundProducto = true;
        this.fetchProducto();
      }
    }
  }
}
</script>


<style scoped>
.main-input-group:first-child {
  margin-bottom: 0.75rem;
}

i {
  position: relative;
  top: -2px;
  color: #fff;
}
</style>

// angular-client/src/app/components/main-form/financiamiento/financiamiento.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Operacion } from '../../../models/operacion.model';
import { OperacionService } from '../../../services/operacion/operacion.service';
import { Observable, Subscription } from 'rxjs';
import { Producto, TipoFinanciamiento } from '../../../models/producto.model';
import { debounceTime, distinctUntilChanged, map } from 'rxjs/operators';
import { NgbTypeaheadSelectItemEvent } from '@ng-bootstrap/ng-bootstrap';
import { ProductoService } from '../../../services/producto/producto.service';
import { LoadingService } from '../../../services/loading/loading.service';
import { Financiamiento } from '../../../models/financiamiento.model';
import { FinanciamientoService } from '../../../services/financiamiento/financiamiento.service';
import { TipoFinanciamientoService } from '../../../services/tipo-financiamiento/tipo-financiamiento.service';
import { AlertService } from '../../alert';

@Component({
  selector: 'app-financiamiento',
  templateUrl: './financiamiento.component.html',
  styleUrls: ['./financiamiento.component.scss']
})
export class FinanciamientoComponent implements OnInit {

  productStr: string;
  product: Producto;
  productoSub: Subscription;
  tipoFin: TipoFinanciamiento;
  financiamiento: Financiamiento;
  financiamientoSub: Subscription;
  @Input() operacion: Operacion;
  typeaheadFunc: ($text: Observable<string>) => Observable<readonly any[]>;
  productos: Producto[];
  private productosSubscription: Subscription;
  constructor(private operacionService: OperacionService,
              private financiamientoService: FinanciamientoService,
              private productoService: ProductoService,
              private tipoFinService: TipoFinanciamientoService,
              private loadingService: LoadingService,
              private alertService: AlertService) {}

  ngOnInit(): void {
    this.productos = this.productoService.getProductos();
    this.productosSubscription = this.productoService.fetchProductos()
      .subscribe((productos) => {
        this.productos = productos;
        console.log('productos en angular:', this.productos);
      });
    this.financiamientoSub = this.financiamientoService.financiamientoChanged
      .subscribe((financiamiento: Financiamiento) => {
        this.financiamiento = financiamiento;
        console.log(this.financiamiento);
        if (!this.financiamiento) {
          this.product = null;
        }
      });
    this.productoSub = this.productoService.productoChanged
      .subscribe((producto: Producto) => {
        this.product = producto;
      });
    this.tipoFinService.tipoFinChanged
      .subscribe((tipoFin: TipoFinanciamiento) => {
        this.tipoFin = tipoFin;
        console.log(this.tipoFin);
      });
  }

  get producto(): string {
    return '';
  }

  // get valorOp(): string {
  //   return this.financiamiento.valorOperacion ? this.financiamiento.valorOperacion : '';
  // }
  //
  // get fondeador(): string {
  //   return this.financiamiento.fondeador ? this.financiamiento.fondeador : '';
  // }
  //
  // get noPagos(): string {
  //   return this.financiamiento.noPagos ? this.financiamiento.noPagos : '';
  // }
  //
  // get periodicidad(): string {
  //   return this.financiamiento.periodicidad ? this.financiamiento.periodicidad : '';
  // }

  fetchProduct($event: NgbTypeaheadSelectItemEvent): void {
    this.loadingService.setLoading(true);
    this.productoService.productoByName($event.item).subscribe(
      (value) => {
        this.loadingService.setLoading(false);
        this.product = value;
        this.productoService.changeProducto(this.product);
        this.operacionService.modify('producto', value);
      },
      (error) => {
        this.loadingService.setLoading(false);
        this.alertService.showAlert('Error al obtener datos del producto', 'error');
        this.product = null;
        this.operacionService.modify('producto', this.product);
      }
    );
  }

  update(key: string, $event: Event): void {
    this.financiamientoService.modify(key, ($event.target as HTMLInputElement).value);
  }

  onChangeTipoFin($event: Event): void {
    const data = ($event.target as HTMLInputElement).value;
    this.tipoFinService.buscaTipoFin(data);
  }

  search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      map(term => term.length < 2 ? []
        : this.productos
          .map((producto) => producto.producto)
          .filter(v => v.toLowerCase().indexOf(term.toLowerCase()) > -1).slice(0, 10))
    )
}

<!-- Financiamiento -->
<section>
  <div class="section-header">
    Financiamiento
  </div>
  <div class="section-content d-flex flex-column align-items-end">
    <div class="d-flex flex-column mb-3 text-center">
      <label for="input-producto">Producto
        <span class="fas fa-info-circle"
              placement="top"
              ngbTooltip="Escriba nombre del producto"
        ></span>
      </label>
      <div class="main-input-group input-group input-group-sm">
        <input
          id="input-producto"
          type="text"
          style="width: 100px;"
          [value]="producto"
          [ngbTypeahead]="search"
          (selectItem)="fetchProduct($event)"
        >
        <div class="input-group-append">
          <button
            class="icon-btn btn btn-secondary"
            type="button"
            id="button-search-product"
            style="height: 1.5rem;"
          >
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </div><!--d-flex flex-column mr-2-->
    <div class="main-input-group">
      <label for="input-fondeador">Fondeador</label>
      <select id="input-fondeador" [value]="fondeador" (change)="update('fondeador', $event)">
        <option selected disabled value="">Seleccione</option>
        <option value="RP">RP</option>
        <option value="ICM">ICM</option>
        <option value="GDA">GDA</option>
        <option value="CR">CR</option>
      </select>
    </div>
    <div class="main-input-group">
      <label for="input-noPagos">No. Pagos</label>
      <select id="input-noPagos" [value]="noPagos" (change)="update('noPagos', $event)">
        <option selected disabled value="">Seleccione</option>
        <option value="12">12</option>
        <option value="24">24</option>
        <option value="36">36</option>
        <option value="48">48</option>
      </select>
    </div>
    <div class="main-input-group">
      <label for="input-periodicidad">Periodicidad</label>
      <select id="input-periodicidad" [value]="periodicidad" (change)="update('periodicidad', $event)">
        <option selected disabled value="">Seleccione</option>
        <option value="Quincenal">Quincenal</option>
        <option value="Mensual">Mensual</option>
        <option value="Anual">Anual</option>
      </select>
    </div>
    <div class="main-input-group">
      <label for="input-valorOperacion">Valor Operación</label>
      <input class="text-right"
             id="input-valorOperacion"
             type="text"
             [value]="valorOp"
             (input)="update('valorOp', $event)"
      >
    </div>
    <div class="main-input-group" *ngIf="product">
      <label for="input-productoTipo">Producto Tipo</label>
      <select id="input-productoTipo" (change)="onChangeTipoFin($event)">
        <option selected disabled value="0">Seleccione</option>
        <option *ngFor="let tipo of product.tiposFin" [value]="tipo.tipoFin">{{tipo.tipoFin}}</option>
      </select>
    </div>
    <div class="main-input-group">
      <label for="input-tasaAnual">Tasa Anual</label>
      <input id="input-tasaAnual" class="text-center" type="text" [value]="tipoFin?.tasa?.toString() || ''"
             (input)="update('tasaAnual', $event)">
    </div>
    <div style="width: 75px; margin-top: 10px; text-align: center;"><label>Importe</label></div>
    <div class="main-input-group">
      <label for="input-anticipo">Anticipo</label>
      <input id="input-anticipo" class="text-center" type="text" [value]="tipoFin?.anticipo?.toString() || ''">
      <label class="block-label" for="input-impAnticipo"></label>
      <input disabled id="input-impAnticipo" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-seguroDeuda">SeguroDeuda</label>
      <input id="input-seguroDeuda" class="text-center" type="text" [value]="tipoFin?.seguroDeuda?.toString() || ''">
      <label for="input-impSeguroDeuda"></label>
      <input disabled id="input-impSeguroDeuda" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-apertura">Apertura</label>
      <input id="input-apertura" class="text-center" type="text" [value]="tipoFin?.apertura?.toString() || ''">
      <label for="input-impApertura"></label>
      <input disabled id="input-impApertura" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-deposito">Depósito</label>
      <input id="input-deposito" class="text-center" type="text" [value]="tipoFin?.deposito?.toString() || ''">
      <label for="input-impDeposito"></label>
      <input disabled id="input-impDeposito" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-admin">Administración</label>
      <input id="input-admin" class="text-center" type="text" [value]="tipoFin?.admon?.toString() || ''">
      <label for="input-impAdmin"></label>
      <input disabled id="input-impAdmin" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-gps">GPS</label>
      <input id="input-gps" class="text-center" type="text" [value]="tipoFin?.gps?.toString() || ''">
      <label for="input-impGps"></label>
      <input disabled id="input-impGps" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-seguroAuto">SeguroAuto</label>
      <input id="input-seguroAuto" class="text-center" type="text" [value]="tipoFin?.seguroDeuda?.toString() || ''">
      <label for="input-impSeguroAuto"></label>
      <input disabled id="input-impSeguroAuto" type="text">
    </div>
    <div class="main-input-group" style="margin-bottom: 10px;">
      <label for="input-valorRescate">ValorRescate</label>
      <input id="input-valorRescate" class="text-center" type="text" [value]="tipoFin?.vRescate?.toString() || ''">
      <label for="input-impValorRescate"></label>
      <input disabled id="input-impValorRescate" type="text">
    </div>
    <div class="main-input-group">
      <label for="input-descuento">Descuento</label>
      <input id="input-descuento" type="text" [value]="tipoFin?.descuento?.toString() || ''">
      <label for="input-impDescuento"></label>
      <input disabled id="input-impDescuento" type="text">
    </div>
    <div style="text-align: right;"><hr style="border-top: #000000 solid 1px; width: 75px"></div>
    <div class="main-input-group">
      <label for="input-total">Total Primer Pago</label>
      <input id="input-total" type="text">
    </div>
  </div><!-- section-content -->
</section>
