// client/src/components/sections/General.vue
<template>
  <div class="section-content">
    <div class="d-flex">
      <div class="d-flex flex-column mr-2">
        <label for="input-operacion" class="d-block">Operación
          <span class="fas fa-info-circle"
                v-b-tooltip.hover.right="'Buscar operación por número, si no existe, crea uno nuevo'"
          ></span>
        </label>
        <div class="main-input-group input-group input-group-sm">
          <input id="input-operacion"
                type="text"
                :value="numOperacion"
                @input="update('operacion', $event)"
                @keyup.enter="findOperacion()"
                :disabled="foundOperacion">
          <div class="input-group-append">
            <b-button
              type="button" 
              @click="findOperacion()"
              id="button-search"
              style="height: 1.5rem;"
              variant="secondary"
            >
              <i class="fas fa-check"></i>
            </b-button>
          </div>
        </div>
      </div>
      <div class="main-input-group">
        <label for="input-fecha">Fecha</label>
        <input id="input-fecha" type="text" :value="operacion.fecha" @input="update('fecha', $event)">
      </div>
      <div class="main-input-group">
        <label for="input-folio">Folio Com.</label>
        <input id="input-folio" type="text" :value="operacion.folio" @input="update('folio', $event)">
      </div>
      <div class="main-input-group d-block">
        <label for="input-refPagos">Referencia Pagos</label>
        <input id="input-refPagos" type="text" :value="operacion.referencia" @input="update('referencia', $event)">
      </div>
    </div>
    <div class="d-flex">
      <div class="main-input-group d-block">
        <label for="input-cliente">Cliente</label>
        <input id="input-cliente" type="text" :value="operacion.dePara" @input="update('dePara', $event)">
      </div>
    </div>
    <div class="d-flex">
      <div class="main-input-group">
        <label for="input-persona">Persona</label>
        <b-select 
          size="sm" 
          id="input-persona" type="text" :value="operacion.persona" @input="update('persona', $event)">
          <b-select-option>Física</b-select-option>
          <b-select-option>Moral</b-select-option>
        </b-select>
      </div>
      <div class="main-input-group d-block">
        <label for="input-personaDesc">Descripción</label>
        <input id="input-personaDesc" type="text" :value="operacion.descripcion" @input="update('descripcion', $event)">
      </div>
    </div>
    <div class="d-flex">
      <div class="main-input-group d-block">
        <label for="input-asesor">Asesor</label>
        <input id="input-asesor" type="text" :value="operacion.promotor" @input="update('promotor', $event)">
      </div>
    </div>
  </div>
</template>

<script>
import { mapState, mapActions, mapMutations } from 'vuex';
export default {
  name: 'General',
  data() {
    return {
      numOperacionDisabled: false,
      foundOperacion: false,
      operacion: {
        operacion: 0,
        fecha: '',
        folio: '',
        referencia: '',
        dePara: '',
        persona: '',
        descripcion: '',
        promotor: '',
      },
    }
  },
  computed: {
    ...mapState(['finanzas']),
    numOperacion() {
      return this.$store.state.operacionPost.operacion;
    }
  },
  methods: {
    ...mapMutations(['setOperacionPost','operacionClear', 'modifyCurrentOperacion']),
    ...mapActions(['postOperacion']),
    update(key, event) {
      this.operacion[key] = event.target.value;
      this.setOperacionPost({ [key]: event.target.value });
    },
    clearContent() {
      this.operacion = {};
    },
    findOperacion() {
      if (this.foundOperacion) {
        this.foundOperacion = !this.foundOperacion;
        return;
      }
      const operacionExiste = this.finanzas.find((fin) => fin.operacion === parseInt(this.numOperacion));
      if (operacionExiste) {
        // fill form
        console.log('Found operacion: ', operacionExiste);
        const {
          numero,
          fecha,
          folio,
          referencia,
          dePara,
          persona,
          descripcion,
          promotor
        } = operacionExiste;
        this.operacion = {
          numero,
          fecha,
          folio,
          referencia,
          dePara,
          persona,
          descripcion,
          promotor
        }
        this.foundOperacion = true;
        this.numOperacionDisabled = true;
        this.setOperacionPost(this.operacion);
      } else {
        this.foundOperacion = false;
        this.numOperacionDisabled = false;
        this.setOperacionPost(this.operacion);
        this.postOperacion();
      }
    },
    handleClickInputOperacion() {
      console.log('click in input...');
      if (this.foundOperacion) {
        this.foundOperacion = false;
        this.numOperacionDisabled = false;
      }
    }
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

label {
  display: block;
  text-align: left;
}

.main-input-group {
  flex-wrap: nowrap;
}

.main-input-group:not(:last-child) {
  margin-right: 4px;
}

.main-input-group:nth-child(3) input {
  width: 100px;
}

.d-block {
  display: block;
  width: 100%;
}

.d-block input {
  width: 100%;
}

a {
  color: #42b983;
}

i {
  position: relative;
  top: -2px;
  color: #fff;
}
</style>

// angular-client/src/app/components/main-form/general/general.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Operacion } from '../../../models/operacion.model';
import { OperacionService } from '../../../services/operacion/operacion.service';
import { LoadingService } from '../../../services/loading/loading.service';
import { AlertService } from '../../alert';

@Component({
  selector: 'app-general',
  templateUrl: './general.component.html',
  styleUrls: ['./general.component.scss']
})
export class GeneralComponent implements OnInit {

  indexOperacion: number;
  editMode: boolean;
  @Input() operacion: Operacion;
  constructor(private operacionService: OperacionService,
              private loadingService: LoadingService,
              private alertService: AlertService) {
  }

  ngOnInit(): void {
  }

  get numOperacion(): string {
    return this.operacion.numOperacion ? this.operacion.numOperacion : '';
  }

  get fecha(): string {
    return typeof this.operacion.fecha === 'string' ? this.operacion.fecha : '';
  }

  get folio(): string {
    return typeof this.operacion.folio === 'string' ? this.operacion.folio : '';
  }

  get refPagos(): string {
    return typeof this.operacion.referenciaPagos === 'string' ? this.operacion.referenciaPagos : '';
  }

  get cliente(): string {
    return typeof this.operacion.cliente === 'string' ? this.operacion.cliente : '';
  }

  get persona(): string {
    return typeof this.operacion.persona === 'string' ? this.operacion.persona : '';
  }

  get descripcion(): string {
    return typeof this.operacion.descripcion === 'string' ? this.operacion.descripcion : '';
  }

  get asesor(): string {
    return typeof this.operacion.asesor === 'string' ? this.operacion.asesor : '';
  }

  handleInput($event: Event): void {
    const inputElValue = ($event.target as HTMLInputElement).value;
    console.log(this.numOperacion, inputElValue);
    if (this.checkIfChangedOrBlank(inputElValue)) {
      this.cleanup();
    } else {
      this.findOperacion();
    }
  }

  findOperacion(): void {
    console.log('finding...');
    this.loadingService.setLoading(true);
    this.operacionService.queryNumOperacion(this.numOperacion).subscribe(
      (value) => {
        console.log(value);
        this.loadingService.setLoading(false);
        this.alertService.showAlert('Found operación!');
      },
      (error) => {
        this.loadingService.setLoading(false);
        console.log(error);
        this.alertService.showAlert('No se encontró operación, creando nueva', 'info');
        this.operacionService.createOperacion(this.numOperacion);
      }
    );
  }

  checkIfChangedOrBlank(value: string): boolean {
    if (this.operacion.numOperacion !== value) {
      return true;
    }
    if (this.numOperacion.length === 0) {
      console.log('Changed to empty, cleaning up...');
      return true;
    }
    return false;
  }

  update(key: string, $event: Event): void {
    this.operacionService.modify(key, ($event.target as HTMLInputElement).value);
  }

  cleanup(): void {
    this.operacionService.clear();
  }
}

<!-- Alta - Baja - Edición de Operaciones -->
<div class="section-content general-form-group">
  <div class="d-flex">
    <div class="d-flex flex-column mr-2">
      <label for="input-operacion" class="d-block">Operación
        <span class="fas fa-info-circle"
              placement="top" ngbTooltip="Buscar operación por número, si no existe, crea uno nuevo"
        ></span>
      </label>
      <div class="main-input-group input-group input-group-sm">
        <input
          autocomplete="off"
          id="input-operacion"
          type="text"
          [value]="numOperacion"
          (input)="inputNumOperacion = $event.target.value"
          (change)="findOperacion()"
        >
        <div class="input-group-append">
          <button
            class="icon-btn btn btn-secondary"
            type="button"
            id="button-search"
            style="height: 1.5rem;"
            (click)="findOperacion()"
          >
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="main-input-group">
      <label for="input-fecha">Fecha</label>
      <input autocomplete="off"
             id="input-fecha"
             placeholder="DD-MMM-AA"
             type="text"
             [value]="fecha"
             (input)="onInput($event.target.value)"
             (change)="dateFormat(textFecha)"
      >
    </div>
    <div class="main-input-group">
      <label for="input-folio">Folio Com.</label>
      <input autocomplete="off"
             id="input-folio"
             type="text"
             [value]="folio"
             (input)="update('folio', $event)"
      >
    </div>
    <div class="main-input-group d-block">
      <label for="input-refPagos">Referencia Pagos</label>
      <input autocomplete="off"
             id="input-refPagos"
             type="text"
             [value]="refPagos"
             (input)="update('refPagos', $event)"
      >
    </div>
  </div>
  <div class="d-flex">
    <div class="main-input-group d-block">
      <label for="input-cliente">Cliente</label>
      <input autocomplete="off"
             id="input-cliente"
             type="text"
             [value]="cliente"
             (input)="update('cliente', $event)"
      >
    </div>
  </div>
  <div class="d-flex">
    <div class="main-input-group" style="width: 80px">
      <label for="input-persona">Persona</label>
      <select
        class="w-100"
        id="input-persona"
        [value]="persona"
        (input)="update('persona', $event)"
      >
        <option>Física</option>
        <option>Moral</option>
      </select>
    </div>
    <div class="main-input-group d-block w-100">
      <label class="d-block" for="input-personaDesc">Descripción</label>
      <input class="w-100"
             id="input-personaDesc"
             type="text"
             [value]="descripcion"
             (input)="update('descripcion', $event)"
             autocomplete="off"
      >
    </div>
  </div>
  <div class="d-flex">
    <div class="main-input-group d-block">
      <label for="input-asesor">Asesor</label>
      <input id="input-asesor"
             type="text"
             [value]="asesor"
             (input)="update('asesor', $event)"
             autocomplete="off"
      >
    </div>
  </div>
</div>
