// client/src/views/Home.vue
<template>
  <div class="home d-inline-flex">
    <div class="main-form-container d-flex justify-content-center">
      <main-form @clickHeader="extensionActive = !extensionActive"></main-form>
      <extension-form v-if="extensionActive"></extension-form>
    </div>
    <v-d-nav @navChanged="currentVD = $event"></v-d-nav>
    <div class="vd-container">
      <v-d-operaciones v-if="currentVD === 'operaciones'"></v-d-operaciones>
      <v-d-cotizaciones v-if="currentVD === 'cotizaciones'"></v-d-cotizaciones>
      <alta-cliente v-if="currentVD === 'altaCliente'"></alta-cliente>
      <manejo-cliente v-if="currentVD === 'manejoCliente'"></manejo-cliente>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import MainForm from '@/components/MainForm.vue';
import VDNav from '@/components/nav/VDNav.vue';
import VDOperaciones from '@/components/VDOperaciones.vue';
import VDCotizaciones from '@/components/VDCotizaciones.vue';
import ExtensionForm from '@/components/ExtensionForm.vue'; // @ is an alias to /src
import AltaCliente from '@/components/AltaCliente.vue';
import ManejoCliente from '@/views/ManejoCliente.vue';

@Component({
  components: {
    ManejoCliente,
    ExtensionForm,
    VDCotizaciones,
    VDOperaciones,
    VDNav,
    MainForm,
    AltaCliente
  },
})
export default class Home extends Vue {
  private currentVD = 'operaciones';
  private extensionActive = false;
}
</script>

<style scoped>

</style>

// angular-client/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  currentVD = 'operaciones';
  constructor() { }

  ngOnInit(): void {
  }

}

<div class="home d-inline-flex overflow-x-auto">
  <app-main-form class="main-form-container d-flex justify-content-center"></app-main-form>
  <app-vd-nav (navChanged)="currentVD = $event"></app-vd-nav>
  <div class="vd-container" [ngSwitch]="currentVD">
    <app-vd-operaciones *ngSwitchCase="'operaciones'"></app-vd-operaciones>
    <app-vd-cotizaciones *ngSwitchCase="'cotizaciones'"></app-vd-cotizaciones>
    <app-vd-desglose *ngSwitchCase="'desglose'"></app-vd-desglose>
    <app-vd-alta-cliente *ngSwitchCase="'altaCliente'"></app-vd-alta-cliente>
    <app-vd-manejo-cliente *ngSwitchCase="'manejoCliente'"></app-vd-manejo-cliente>
    <app-vd-operaciones *ngSwitchDefault></app-vd-operaciones>
  </div>

</div>
