// angular-client/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor(private router: Router,
              private authService: AuthService) { }

  ngOnInit(): void {
  }

  async login() {
    this.authService.login();
    await this.router.navigate(['/home']);
  }
}

<div class="container">
  <div class="pt-5 row justify-content-center">
    <h1>ChequeraTax</h1>
  </div>
  <div class="row justify-content-center">
    <h5>Inicia Sesión</h5>
  </div>
  <div class="p-5 row">
    <div class="col"></div>
    <div class="col">
      <form>
        <div class="form-group">
          <label for="email">Usuario</label>
          <input type="email" class="form-control" id="email" />
        </div>
        <div class="form-group">
          <label for="password">Contraseña</label>
          <input type="password" class="form-control" id="password" />
        </div>
        <div class="form-group form-check">
          <input type="checkbox" id="remember" />
          <label class="form-check-label" for="remember"
          >Manten mi sesión inciada</label
          >
        </div>
        <div class="text-center">
          <button (click)="login()" type="submit" class="btn btn-success" id="submit">
            Iniciar sesión
          </button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
</div>

// client/src/components/Log-in.vue
<template>
  <div class="p-5 row">
    <div class="col"></div>
    <div class="col">
      <form>
        <div class="form-group">
          <label for="email">Usuario</label>
          <input type="email" class="form-control" id="email" />
        </div>
        <div class="form-group">
          <label for="password">Contraseña</label>
          <input type="password" class="form-control" id="password" />
        </div>
        <div class="form-group form-check">
          <input type="checkbox" id="remember" />
          <label class="form-check-label" for="remember"
            >Manten mi sesión inciada</label
          >
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-success" id="submit">
            Iniciar sesión
          </button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
</template>

<style scoped>
#email {
  text-align: center;
}
#password {
  text-align: center;
}
</style>
