// client/src/components/ConfigForm/CalifBuro.vue
<template>
<section>
  <div class="section-header">Calificación Buró de Crédito</div>
  <div class="section-content">
    <div class="main-main-input-group d-flex justify-content-between">
      <div class="main-input-group">
        <label class="d-block" for="config-buro-clave">Clave</label>
        <input id="config-buro-clave">
      </div>
      <div class="d-flex justify-content-center">
        <div class="main-input-group mr-50">
          <label class="d-block" for="config-buro-diasMin">DíasMínimo</label>
          <input id="config-buro-diasMin">
        </div>
        <div class="main-input-group text-align-left">
          <label class="d-block" for="config-buro-diasMax">DíasMáximo</label>
          <input id="config-buro-diasMax">
        </div>
      </div>
      <div class="main-input-group">
        <label class="d-block" for="config-buro-color">Color</label>
        <input id="config-buro-color">
      </div>
    </div>
  </div>
</section>
</template>

<script>
export default {
name: "CalifBuro"
}
</script>

<style scoped>

</style>

// angular-client/src/app/components/config-form/calif-buro/calif-buro.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-calif-buro',
  templateUrl: './calif-buro.component.html',
  styleUrls: ['./calif-buro.component.scss']
})
export class CalifBuroComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<section>
  <div class="section-header">Calificación Buró de Crédito</div>
  <div class="section-content">
    <div class="main-main-input-group d-flex justify-content-between">
      <div class="main-input-group">
        <label class="d-block" for="config-buro-clave">Clave</label>
        <input id="config-buro-clave">
      </div>
      <div class="d-flex justify-content-center">
        <div class="main-input-group mr-50">
          <label class="d-block" for="config-buro-diasMin">DíasMínimo</label>
          <input id="config-buro-diasMin">
        </div>
        <div class="main-input-group text-align-left">
          <label class="d-block" for="config-buro-diasMax">DíasMáximo</label>
          <input id="config-buro-diasMax">
        </div>
      </div>
      <div class="main-input-group">
        <label class="d-block" for="config-buro-color">Color</label>
        <input id="config-buro-color">
      </div>
    </div>
  </div>
</section>
